services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ragops-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ragops-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: ragops-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - ragops-network

networks:
  ragops-network:
    external: true
